import os
from datetime import datetime

from flask import Blueprint, send_file, abort
from flask_login import login_required, current_user

from models.contacts import load_contacts
from utils.band import get_band

export_bp = Blueprint("export", __name__)


@export_bp.route("/export")
@login_required
def export():
    contacts = load_contacts(current_user.id)

    if not contacts:
        abort(404, description="No hay contactos para exportar.")

    op_id = current_user.id
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    filename = f"contacts-{op_id}-{timestamp}.adi"
    filepath = f"/tmp/{filename}"

    lines = ["Generated by MiniLog by LU2FTI\n"]

    for c in contacts:
        if len(c) < 6:
            continue

        band     = get_band(c[3])
        notes    = c[4] if len(c) > 4 else ""
        qso_date = c[0].split()[0].replace("-", "")

        try:
            time_on = datetime.strptime(c[0], "%Y-%m-%d %H:%M:%S").strftime("%H%M%S")
        except ValueError:
            time_on = "000000"

        def field(tag, value):
            return f"<{tag}:{len(value)}>{value} "

        line = (
            field("station_callsign", op_id)
            + field("call", c[1])
            + field("qso_date", qso_date)
            + field("time_on", time_on)
            + field("band", band)
            + field("freq", c[3])
            + field("mode", c[2])
            + field("notes", notes)
            + "<eor>\n"
        )
        lines.append(line)

    with open(filepath, "w", encoding="utf-8") as f:
        f.writelines(lines)

    return send_file(filepath, as_attachment=True, download_name=filename)
