server {
    listen 80;

    # Capa extra de seguridad (opcional, comentar si no se usa)
    auth_basic "MiniLog Restricted";
    auth_basic_user_file /etc/nginx/htpasswd;

    # Pasar el usuario de nginx a Flask (útil para logs)
    proxy_set_header X-Remote-User $remote_user;

    location / {
        proxy_pass         http://minilog:5000;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_read_timeout 30s;
    }
}
